end/demo1/bookdemo/bookdemo/urls.py
# 项目的所有路由地址配置文件
# admin路由是 django 自带的后台管理路由

from django.contrib import admin
from django.urls import path,include

#路由 网址 每一个网址均需要绑定视图函数 视图函数给与页面返回
# 每一个路由都需要和视图函数绑定
# mvt V视图函数  3个作用 接受请求  处理数据  返回响应

# from django.http import HttpResponse
# def index(request):
#     return HttpResponse("这里是首页")
# def list(request):
#     return HttpResponse("这是列表页")
# def jsondata(request):
#     return HttpResponse("{'name':'lijiabin','age':'25'}")


urlpatterns = [
    path('admin/', admin.site.urls),
    #使用path将booktest的路由 进行包含

    path('polls/',include('polls.urls',namespace='polls')),
    path('',include('booktest.urls',namespace='booktest')),


    # 将admin路由与index视图数据绑定
    # path('index/',index),
    # path('list/',list),
    # path('json/',jsondata)
]

end/demo1/bookdemo/booktest/urls.py
# 引入路由绑定函数
from django.conf.urls import url
from . import views

app_name = 'booktest'

# 2每一路由文件中必须编写路由数据
urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^detail/(\d+)/',views.detail,name='detail'),


    url(r'^addbook/$',views.addbook,name='addbook'),
    url(r'^editbook/(\d+)',views.editbook,name='editbook'),
    url(r'^deletebook/(\d+)/$',views.deletebook,name='deletebook'),

    url(r'^addhero/(\d+)/$',views.addhero,name='addhero'),
    url(r'^edithero/(\d+)/$',views.edithero,name='edithero'),
    url(r'^deletehero/(\d+)/$',views.deletehero,name='deletehero'),



]

end/demo1/bookdemo/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    # 如果在正则表达式中有正则分组  那么在视图中必须得有响应的形参
    # 如果正则分组有别名 那么形参名一定要和正则分组别名一致
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^result/(\d+)/$',views.result,name='result')

]

end/demo1/bookdemo/templates/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
</head>
<body>
    <div class="conter">
        {# 向当前页面的路由发起post请求 #}
        <form action="#" method="post">
            书籍名字: <input type="text" name="booktitle" placeholder="输入书籍">
            <br>
            书籍价格: <input type="text" name="bookprice" placeholder="输入价格">
            <br>
           出版时间: <input type="date" name="bookpub_date" >
            <br>
            <input type="submit" value="提交书籍">

        </form>

    </div>
</body>
</html>

end/demo1/bookdemo/templates/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加英雄</title>
</head>
<body>
    <div class="conter">
        {# 向当前页面的路由发起post请求 #}
        <form action="#" method="post">
            英雄名字: <input type="text" name="heroname" placeholder="输入角色名">
            <br>
            英雄技能: <input type="text" name="herocontent" placeholder="输入技能">
            <br>
            性别: <input type="radio" name="sex" value="female" checked> 女
                    <input type="radio" name="sex" value="female">  男
            <br>
            <input type="submit" value="提交英雄">

        </form>

    </div>
</body>
</html>

end/demo1/bookdemo/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="center">
        <h1>这里是详情页</h1>
        <h2>书名:{{book.title}}</h2>
        <h3>关键人物集:</h3>
        <ul>
            {% for hero in book.hero_set.all %}
                <li>
                    {{hero.name}} -- {{hero.gender}} -- {{hero.content}}
                    <a href="{% url 'booktest:deletehero' hero.id %}">删除</a>
                    <a href="{% url 'booktest:edithero' hero.id %}">修改</a>
                </li>
            {% endfor %}
        </ul>
         <a href="{% url 'booktest:addhero' book.id %}"> 添加英雄</a>
         <a href="{% url 'booktest:index' %}">返回首页</a>
    </div>
</body>
</html>

end/demo1/bookdemo/templates/editbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑书籍</title>
</head>
<body>
    <form action="#" method="post">
        书籍名字：<input type="text" name="booktitle" value="{{book.title}}">
        <br>
        书籍价格：<input type="text" name="bookprice" value="{{book.price}}">
        <br>
        出版日期：<input type="date" name="bookpub_date">
        <br>
        <input type="submit" value="提交修改">

    </form>
</body>
</html>

end/demo1/bookdemo/templates/edithero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑英雄</title>
</head>
<body>
    <form action="#" method="post">
        英雄名字：<input type="text" name="heroname" value="{{hero.name}}">
        <br>
        英雄技能：<input type="text" name="herocontent" value="{{hero.content}}">
        <br>
        {% if hero.gender == 'male' %}
            英雄的性别 <input type="radio" name="sex" value="male" checked> 男 <input type="radio" name="sex" value="female"> 女
        {% else %}
            英雄的性别 <input type="radio" name="sex" value="male"> 男 <input type="radio" name="sex" value="female" checked> 女
        {% endif %}
        <br>
        <input type="submit" value="提交修改">

    </form>
</body>
</html>

end/demo1/bookdemo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>

     <div class="center ">
         </h1>这是首页 <a href="{% url 'polls:index' %}">进入投票页面</a></h1>
         <div >
             <img src="/static/img/公众号.jpg" alt="">

         <h2>共有书籍({{books.count}})</h2>
         <ul>
            {% for book in books %}
             <li>
                 <a href="{% url 'booktest:detail' book.id %}">{{book.id}} -- {{book.title}} -- {{book.price}}--{{book.pub_date}}</a>
                 <a href="{% url 'booktest:editbook' book.id %}">修改</a>
                 <a href="{% url 'booktest:deletebook' book.id %}">删除</a>

             </li>
             {%endfor%}
             <a href="{% url 'booktest:addbook' %}">添加书籍</a>
         </ul>
         </div>
     </div>
</body>
</html>