end/demo1/bookdemo/bookdemo/urls.py
# 项目的所有路由地址配置文件
# admin路由是 django 自带的后台管理路由

from django.contrib import admin
from django.urls import path,include

#路由 网址 每一个网址均需要绑定视图函数 视图函数给与页面返回
# 每一个路由都需要和视图函数绑定
# mvt V视图函数  3个作用 接受请求  处理数据  返回响应

# from django.http import HttpResponse
# def index(request):
#     return HttpResponse("这里是首页")
# def list(request):
#     return HttpResponse("这是列表页")
# def jsondata(request):
#     return HttpResponse("{'name':'lijiabin','age':'25'}")


urlpatterns = [
    path('admin/', admin.site.urls),
    #使用path将booktest的路由 进行包含

    path('polls/',include('polls.urls',namespace='polls')),
    path('',include('booktest.urls',namespace='booktest')),


    # 将admin路由与index视图数据绑定
    # path('index/',index),
    # path('list/',list),
    # path('json/',jsondata)
]

end/demo1/bookdemo/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    # 如果在正则表达式中有正则分组  那么在视图中必须得有响应的形参
    # 如果正则分组有别名 那么形参名一定要和正则分组别名一致
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^result/(\d+)/$',views.result,name='result')

]

end/demo1/bookdemo/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    """
    投票问题类
    """
    title = models.CharField(max_length=50, verbose_name="投票问题")
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "投票表"
        verbose_name_plural = verbose_name
        ordering = ["-create_time"]



class Choices(models.Model):
    """
    投票选项类
    """
    content = models.CharField(max_length=50,verbose_name="选项")
    votes = models.PositiveIntegerField(verbose_name="得票数")
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="创建时间")
    question = models.ForeignKey(Question,on_delete=models.CASCADE,related_name='choices',verbose_name="所属问题")

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "选项表"
        verbose_name_plural = "选项表"
        ordering = ["-create_time"]

end/demo1/bookdemo/polls/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse
from .models import *
# Create your views here.


def index(request):
    questions = Question.objects.all()
    return render(request,'polls/index.html',{"questions":questions})

def detail(request,qid):
    if request.method == "GET":
        try:
            question = Question.objects.get(id=qid)
            return render(request, 'polls/detail.html', {"question": question})
        except:
            return HttpResponse("问题不合法")
    elif request.method == "POST":
        choiceid = request.POST.get("num")
        try:
            choice = Choices.objects.get(id=choiceid)
            choice.votes += 1
            choice.save()
            # 返回当前投票问题的投票结果页
            url = reverse("polls:result",args=(qid,))
            # 投票成功 返回投票结果
            return redirect(to=url)

        except:
            return HttpResponse("选项不合法")

def result(request,qid):
    question = Question.objects.get(id=qid)
    return render(request,'polls/result.html',{"question":question})

end/demo1/bookdemo/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票详情</title>
</head>
<body>
    <div >
        <h2> 投票的问题是： {{question.title}} </h2>
        <ul>
            <h3>选项有:</h3>
            <form action="#" method="post">
                {% for c in question.choices.all %}
                    {% if forloop.counter == 1 %}
                        <li><input type="radio" checked name="num" value="{{c.id}}">{{c.content}}</li>
                    {% else %}
                        <li><input type="radio"  name="num" value="{{c.id}}">{{c.content}}</li>
                    {% endif %}

                {% endfor %}

                <input type="submit" value="投票">
            </form>
        </ul>
        <a href="{% url 'polls:index' %}">返回</a>
    </div>

</body>
</html>

end/demo1/bookdemo/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="center">
        <h2>投票问题列</h2>
        <ul>
            {% for q in questions %}
                <li><a href="{% url 'polls:detail' q.id %}"> {{forloop.counter}} .{{q.title}}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

end/demo1/bookdemo/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票结果页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h2>问题是: {{question.title}}</h2>

        <ul>
            <h3>得票情况</h3>
            {% for c in question.choices.all %}
                <li>{{c.content}}   {{c.votes}} 票</li>
            {% endfor %}
        </ul>

        <a href="{% url 'polls:index' %}">返回</a>
    </div>
</body>
</html>